# Generated by Django 4.2.13 on 2024-06-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logradouro", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("bairro", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("admi", "Admin"),
                            ("alun", "Aluno"),
                            ("prof", "Professor"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField(max_length=10)),
                ("periodo", models.IntegerField(max_length=2)),
                ("sala", models.CharField(max_length=20)),
                ("dataAbertura", models.DateField()),
                ("quantidadeAlunos", models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "matricula",
                    models.IntegerField(
                        default="0000000000",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpf", models.IntegerField(default="00000000000", max_length=11)),
                ("nome", models.CharField(max_length=50)),
                ("telefone", models.IntegerField(default=0, max_length=11)),
                (
                    "endereco",
                    models.OneToOneField(
                        default=("n/a", 0, "n/a", "00"),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.endereco",
                    ),
                ),
                (
                    "login",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.login",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("cargaHoraria", models.IntegerField()),
                ("horario", models.DateField()),
                ("professores", models.ManyToManyField(to="core.professor")),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "matricula",
                    models.IntegerField(
                        default="0000000000",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpf", models.IntegerField(default="00000000000", max_length=11)),
                ("nome", models.CharField(max_length=200)),
                ("telefone", models.IntegerField(default=0, max_length=11)),
                ("dataAdmissao", models.DateField(auto_now_add=True)),
                ("turmaCod", models.IntegerField()),
                ("disciplinas", models.ManyToManyField(to="core.disciplina")),
                (
                    "endereco",
                    models.OneToOneField(
                        default=("n/a", 0, "n/a", "00"),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.endereco",
                    ),
                ),
                (
                    "login",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.login",
                    ),
                ),
            ],
        ),
    ]
