# Generated by Django 4.2.13 on 2024-06-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "matricula",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("cpf", models.BigIntegerField(default=0)),
                ("nome", models.CharField(max_length=200)),
                ("telefone", models.CharField(default=0, max_length=11)),
                ("dataAdmissao", models.DateField()),
                ("turmaCod", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "matricula",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("cpf", models.BigIntegerField(default=0)),
                ("nome", models.CharField(max_length=50)),
                ("telefone", models.CharField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("periodo", models.IntegerField(default=0)),
                ("sala", models.CharField(max_length=20)),
                ("dataAbertura", models.DateField()),
                ("quantidadeAlunos", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.aluno",
                    ),
                ),
                ("login", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("aluno", "Aluno"),
                            ("professor", "Professor"),
                        ],
                        max_length=9,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, default=0, primary_key=True, serialize=False
                    ),
                ),
                ("logradouro", models.CharField(max_length=100)),
                ("numero", models.IntegerField(default=0)),
                ("bairro", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
                (
                    "matricula",
                    models.OneToOneField(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.aluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "codigo",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cargaHoraria", models.IntegerField(default=0)),
                ("horario", models.DateField()),
                ("professores", models.ManyToManyField(to="core.professor")),
            ],
        ),
        migrations.AddField(
            model_name="aluno",
            name="disciplinas",
            field=models.ManyToManyField(to="core.disciplina"),
        ),
    ]
