# Generated by Django 4.2.13 on 2024-06-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("admi", "Admin"),
                            ("alun", "Aluno"),
                            ("prof", "Professor"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("cargaHoraria", models.IntegerField()),
                ("horario", models.DateField()),
                ("professores", models.ManyToManyField(to="core.professor")),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("matricula", models.IntegerField(primary_key=True, serialize=False)),
                ("cpf", models.IntegerField()),
                ("nome", models.CharField(max_length=200)),
                ("endereco", models.CharField(max_length=400)),
                ("telefone", models.IntegerField()),
                ("dataAdmissao", models.DateField(auto_now_add=True)),
                ("turmaCod", models.IntegerField()),
                ("disciplinas", models.ManyToManyField(to="core.disciplina")),
                (
                    "login",
                    models.ForeignKey(
                        default=("00", "null", "null", "n/a"),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.login",
                    ),
                ),
            ],
        ),
    ]
