# Generated by Django 4.2.13 on 2024-06-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("aluno", "Aluno"),
                    ("professor", "Professor"),
                ],
                max_length=9,
            ),
        ),
    ]
