# Generated by Django 4.2.13 on 2024-06-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_login_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login",
            old_name="type",
            new_name="access",
        ),
        migrations.RenameField(
            model_name="login",
            old_name="email",
            new_name="login",
        ),
    ]
