# Generated by Django 4.2.13 on 2024-06-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_type_login_access_rename_email_login_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=models.BigIntegerField(default="00000000000", max_length=11),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name="professor",
            name="cpf",
            field=models.BigIntegerField(default="00000000000", max_length=11),
        ),
        migrations.AlterField(
            model_name="professor",
            name="telefone",
            field=models.CharField(default=0, max_length=11),
        ),
    ]
